Repository riscv/riscv-debug-spec, pull requests merged in 2023-04, with the labels that each got.

#831 Remove references to the timing bit.
  debugger_implementation.tex
  xml/core_registers.xml
Labels: 1.0

#832 Document native single step options.
  debugger_implementation.tex
Labels: 1.0+

#833 Rename dtmc.dmihardreset field to dtmhardreset
  xml/jtag_registers.xml
Labels: 1.0+

#834 Clarify action 8/9 signal TM external triggers.
  Sdtrig.tex
  xml/hwbp_registers.xml
Labels: 1.0+

#821 Describe how CMO instructions match triggers.
  Sdtrig.tex
  riscv-debug-spec.tex
Labels: 1.0

#839 Reentrant trigger prevention inhibits match *or fire*
  Sdtrig.tex
Labels: Bug fix, 1.0
