Repository riscv/riscv-debug-spec, pull requests merged in 2023-08, with the labels that each got.

#868 Program Buffer: Clarify requirements for case progbufsize==1
  debug_module.tex
Labels: Clarification, 1.0

#869 AR: Don't use "non-existent" in reference to register.
  Sdext.tex
  Sdtrig.tex
  debug_module.tex
  introduction.tex
  xml/jtag_registers.xml
Labels: Clarification, 1.0

#867 AR: Clarify message register uses.
  debug_module.tex
  xml/abstract_commands.xml
  xml/dm_registers.xml
Labels: Clarification, Bug fix, 1.0

#865 AR: Define "native debug" in Background section.
  introduction.tex
Labels: Clarification, 1.0

#871 Clarify that each DMI address points at a 32-bit register.
  debug_module.tex
Labels: Clarification, 1.0

#872 Sdtrig must implement at least one trigger.
  Sdtrig.tex
Labels: Bug fix, 1.0
