Repository riscv/riscv-debug-spec, pull requests merged in 2024-04, with the labels that each got.

#997 Fix various issues with hyperlinks within the document.
  debug_module.adoc
  debugger_implementation.adoc
  dtm.adoc
  introduction.adoc
  registers.py
  riscv-debug-header.adoc
  xml/core_registers.xml
  xml/dm_registers.xml
  xml/jtag_registers.xml
  xml/sw_registers.xml
Labels: Formatting Issue, 1.0

#1007 Asciidoc conversion fixes for appendix A
  implementations.adoc
Labels: Bug fix, 1.0

#1006 Asciidoc conversion fixes for Sdext
  Sdext.adoc
Labels: Bug fix, 1.0

#1003 dmactive is part of dmcontrol, and debug module version is from dmstatus
  debug_module.adoc
Labels: Bug fix, 1.0

#1010 Remove an extra 'already' in [5.7. Trigger Module Registers]
  Sdtrig.adoc
Labels: Formatting/Typo, 1.0

#1020 "Native Triggers": Add in mepc/mcause back in.
  Sdtrig.adoc
Labels: Formatting/Typo, 1.0

#1022 Restore references to `mhartid` in `debug_module.adoc`
  debug_module.adoc
Labels: Formatting/Typo, 1.0
