Repository riscv/riscv-debug-spec, pull requests merged in 2024-03, with the labels that each got.

#979 Fix minor AsciiDoc conversion problem.
  debug_module.adoc
  xml/hwbp_registers.xml
Labels: Formatting Issue, 1.0

#982 Fix asciidoc conversion for DXLEN definition.
  introduction.adoc
Labels: 1.0, asciidoc

#978 Clarify textra behavior when XLEN changes.
  xml/hwbp_registers.xml
Labels: Clarification, 1.0

#951 Fix contradictory req. for ndmresetpending
  debug_module.adoc
Labels: Bug fix, 1.0

#981 Make the data of the *context registers 32 bits wide.
  introduction.adoc
  xml/hwbp_registers.xml
Labels: Backwards Incompatible Change, Clarification, 1.0

#987 Load data before trigger priority was ambiguous.
  Sdtrig.adoc
Labels: Bug fix, 1.0
