Repository riscv/riscv-debug-spec, pull requests merged in 2024-05, with the labels that each got.

#998 Add support for Smdbltrp.
  xml/core_registers.xml
Labels: Feature, 1.0

#988 1.0.0-rc2
  Sdext.adoc
  Sdtrig.adoc
  debug_module.adoc
  introduction.adoc
  riscv-debug-header.adoc
  xml/hwbp_registers.xml
Labels: 1.0

#1030 Restore references to `command.cmdtype` and `tab:cmdtype` table
  debug_module.adoc
Labels: 1.0, asciidoc

#1031 Restore reference to `dmstatus.impebreak`
  debug_module.adoc
Labels: 1.0, asciidoc

#1032 Fix a typo in [3.12. Security]
  debug_module.adoc
Labels: Formatting/Typo, 1.0

#1033 Restore references to `pc` in [3.8. Program Buffer]
  debug_module.adoc
Labels: Formatting/Typo, 1.0

#1035 Fix formatting for `mconfigptr`
  xml/dm_registers.xml
Labels: Formatting/Typo, 1.0

#1036 Fix references to `sbcs.sbaccess64/128`
  xml/dm_registers.xml
Labels: 1.0, asciidoc

#1037 Restore reference to `time`
  Sdext.adoc
Labels: 1.0, asciidoc

#1038 Replace single quotes with backticks in `mstatus` reference
  Sdext.adoc
Labels: Formatting/Typo, 1.0

#1039 Replace "count" with a reference to 'icount.count'
  Sdext.adoc
Labels: Formatting/Typo, 1.0

#1024 Eliminate redundant statement about AMO's stored value availability
  Sdtrig.adoc
Labels: Clarification, 1.0

#1023 Clarify timing support suggestion for a chain of mcontrol load triggers
  xml/hwbp_registers.xml
Labels: Clarification, 1.0

#1009 Simplify WARL description for dmode=0 and action=1.
  Sdtrig.adoc
Labels: Clarification, 1.0
