Repository riscv/riscv-debug-spec, pull requests merged in 2025-02, with the labels that each got.

#1101 Fix yet another asciidoc conversion problem
  Sdtrig.adoc
  debug_module.adoc
  introduction.adoc
Labels: asciidoc

#1077 Clarify that "an operation" is a DMI operation.
  xml/jtag_registers.xml
Labels: Clarification

#1078 Remove outdated "publish" workflow
  .github/workflows/publish.yml
Labels: codegen

#1100 Fix the link to `dmstatus.version` in "Minor Changes from 0.13 to 1.0"
  introduction.adoc
Labels: asciidoc

#1092 add dependabot to create PR to update the submodules to latest
  .github/dependabot.yml
Labels: codegen
